### ISSUE TITLE
Duplication of genes - JSONObject["name"] not found

### ISSUE THREAD

**Issue by MoffMade** [TAMU-CPT/Apollo#5]
Jolene and Toni have reported problems duplicating genes on Apollo. Checking the logs revealed the JSONObject not found error. This was replicated on several phage organisms (T5, C2, PBSX, ZW6) on both Jolene's and Toni's user account. 

> 10/22/2018 2:26:15 PM2018-10-22 19:26:15,545 [clientInboundChannel-2] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
> 10/22/2018 2:26:15 PMjava.lang.reflect.InvocationTargetException
> 10/22/2018 2:26:15 PM	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1144)
> 10/22/2018 2:26:15 PM	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1143)
> 10/22/2018 2:26:15 PM	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1139)
> 10/22/2018 2:26:15 PM	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
> 10/22/2018 2:26:15 PM	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
> 10/22/2018 2:26:15 PM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 10/22/2018 2:26:15 PM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 10/22/2018 2:26:15 PM	at java.lang.Thread.run(Thread.java:748)
> 10/22/2018 2:26:15 PMCaused by: org.codehaus.groovy.grails.web.json.JSONException: JSONObject["name"] not found.
> 10/22/2018 2:26:15 PM	at org.bbop.apollo.FeatureService._do_generateTranscript(FeatureService.groovy:193)
> 10/22/2018 2:26:15 PM	at org.bbop.apollo.RequestHandlingService.$tt__addTranscript(RequestHandlingService.groovy:651)
> 10/22/2018 2:26:15 PM	... 8 more

**Comment by MoffMade** [comment]
Not occurring since version update, closing
